[build]
  command = "cd .. && yarn install --frozen-lockfile --ignore-engines --production=false && yarn workspace letscube-client build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.18.2"
  YARN_VERSION = "1.22.22"

[context.deploy-preview]
  ignore = "exit 0"
