const NOTIFICATION_TYPES = Object.freeze({
  FRIEND_REQUEST: 'friend_request',
  FRIEND_REQUEST_ACCEPTED: 'friend_request_accepted',
  ROOM_INVITATION: 'room_invitation',
});

const NOTIFICATION_SOURCE_TYPES = Object.freeze({
  FRIEND_RELATIONSHIP: 'friend_relationship',
  ROOM_INVITATION: 'room_invitation',
});

const SOURCE_TYPE_BY_NOTIFICATION_TYPE = Object.freeze({
  [NOTIFICATION_TYPES.FRIEND_REQUEST]: NOTIFICATION_SOURCE_TYPES.FRIEND_RELATIONSHIP,
  [NOTIFICATION_TYPES.FRIEND_REQUEST_ACCEPTED]: NOTIFICATION_SOURCE_TYPES.FRIEND_RELATIONSHIP,
  [NOTIFICATION_TYPES.ROOM_INVITATION]: NOTIFICATION_SOURCE_TYPES.ROOM_INVITATION,
});

const isKnownNotification = ({ sourceType, type } = {}) => (
  SOURCE_TYPE_BY_NOTIFICATION_TYPE[type] === sourceType
);

module.exports = {
  isKnownNotification,
  NOTIFICATION_SOURCE_TYPES,
  NOTIFICATION_TYPES,
  SOURCE_TYPE_BY_NOTIFICATION_TYPE,
};
